//PRODUCT ACTIONS
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_ID = "FETCH_PRODUCT_ID";
export const FETCH_PRODUCT_USER_ID = "FETCH_PRODUCT_USER_ID";
export const ADD_PRUDUCT = "ADD_PRUDUCT";
export const UPDATE_PRUDUCT = "UPDATE_PRUDUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const NEW_PRODUCT = "NEW_PRODUCT";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

//USER ACTIONS
export const FETCH_USER = "FETCH_USER";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";

//ORDER ACTION
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDER_ID = "FETCH_ORDER_ID";
export const FETCH_ORDER_USER_ID = "FETCH_ORDER_USER_ID";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const SEARCH_ORDERS = "SEARCH_ORDERS";
export const NEW_ORDER = "NEW_ORDER";
export const FETCH_ORDERS_ERROR = "FETCH_ORDERS_ERROR";
export const FETCH_ORDER_SELLER_ID = "FETCH_ORDER_SELLER_ID";

//AUTH ACTIONS
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_VERIFY = "USER_VERIFY";
export const USER_EXISTS = "USER_EXISTS";
export const USER_SET = "USER_SET";
export const USER_ERROR = "USER_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const FETCH_USER_ID = "FETCH_USER_ID";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

//CART ACTIONS
export const CART_ADD = "CART_ADD";
export const CART_REMOVE = "CART_REMOVE";
export const CART_CLEAR = "CART_CLEAR";

// ERROR ACTIONS
export const GET_ERRORS = "GET_ERRORS";

//PROFILE REDUCER
export const PROFILE_GET = "PROFILE_GET";
