//PRODUCT ACTIONS
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

//USER ACTIONS
export const FETCH_USER = 'FETCH_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';

//AUTH ACTIONS
export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_VERIFY = 'USER_VERIFY';
export const USER_EXISTS = 'USER_EXISTS';
export const USER_SET = 'USER_SET';
export const USER_ERROR = 'USER_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

//FLASH/ALERT ACTIONS

export const FLASH_ADD = "FLASH_ADD";
export const FLASH_REMOVE = "FLASH_REMOVE";
export const FLASH_REMOVE_ALL = "FLASH_REMOVE_ALL";

