//PRODUCT ACTIONS
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const NEW_PRODUCT = "NEW_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const PRODUCT_INFO = "PRODUCT_INFO";

//USER ACTIONS
export const FETCH_USER = "FETCH_USER";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";

//ORDER ACTION
export const NEW_ORDER = "NEW_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";

//AUTH ACTIONS
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_VERIFY = "USER_VERIFY";
export const USER_EXISTS = "USER_EXISTS";
export const USER_SET = "USER_SET";
export const USER_ERROR = "USER_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const FETCH_USER_ID = "FETCH_USER_ID";
export const FETCH_USER_STATS = "FETCH_USER_STATS";

//CART ACTIONS
export const CART_ADD = "CART_ADD";
export const CART_REMOVE = "CART_REMOVE";
export const CART_CLEAR = "CART_CLEAR";
export const CART_FETCH = "CART_FETCH";

// ERROR ACTIONS
export const GET_ERRORS = "GET_ERRORS";

//PROFILE REDUCER
export const PROFILE_GET = "PROFILE_GET";
